apiVersion: ipam.nddr.yndd.io/v1alpha1
kind: Alloc
metadata:
  name: nokia.default.default.alloc-loopback-leaf1
  namespace: default
spec:
  alloc:
    selector:
    - key: purpose
      value: loopback
    - key: address-family
      value: ipv4
    source-tag:
    - key: node
      value: leaf1