apiVersion: ipam.nddr.yndd.io/v1alpha1
kind: IpamNetworkInstanceIpPrefix
metadata:
  name: ipam-test-ni-default-loopback-ipv6
  namespace: default
spec:
  ipam-name: test
  network-instance-name: default
  ip-prefix:
    prefix: 2000::/64
    tag:
    - key: purpose
      value: loopback